version: "3"

x-logging: &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

services:
  #Reverse proxy. All traffic flows through this
  nginx:
      container_name: nginx
      image: nginx
      restart: unless-stopped
      ports:
         - 80:80
         - 443:443
         - 3100:3100
      volumes:
         - ./nginx:/etc/nginx
         - ./nginx/certificates:/etc/nginx/certificates/
      networks:
         - loki
      logging: *default-logging
  
  #logs get sent here
  loki:
    container_name: "loki"
    image: grafana/loki:2.5.0
    restart: unless-stopped
    user: ${USER_ID:-1000}
    volumes:
      - ./loki:/etc/loki
      - ./loki/data:/tmp/loki/
    command: -config.file=/etc/loki/loki-config.yml
    networks:
    - loki
    logging: *default-logging

  #GUI for viewing logs
  grafana:
      container_name: grafana
      image: grafana/grafana:latest
      restart: unless-stopped
      user: ${USER_ID:-1000}
      volumes:
        - ./grafana:/var/lib/grafana
      environment:
        # GF_<SectionName>_<KeyName>
        GF_DATAPROXY_MAX_IDLE_CONNECTIONS: '1000'
      networks:
      - loki
      logging: *default-logging
  
  #sends logs to loki
  promtail:
    container_name: "promtail"
    image: grafana/promtail:2.4.0
    restart: unless-stopped
    depends_on:
    - loki
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml -config.expand-env=true
    networks:
      - loki
    logging: *default-logging

networks:
   loki: