global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
    
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['prometheus:9090']
- job_name: loki
  static_configs:
  - targets: ['loki:3100']
- job_name: node-exporter
  static_configs:
  - targets: ['172.17.0.1:9100']
  # - targets: ['172.17.0.1:9100']
