positions:
  filename: /tmp/positions.yaml

clients:
   - url: http://${HTTP_AUTH_USERNAME}:${HTTP_AUTH_PASSWORD}@loki:3100/loki/api/v1/push

scrape_configs:
# local machine logs
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels: #custom labels 
      __path__: /var/log/**/*.log
      all: all
      job: varlogs
      host: loggy

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      all: all
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<container_name>(?:[^|]*[^|]))
      source: tag
  - labels:
      stream:
      container_name:
  - labeldrop: # dont include filename in docker logs.. it's too messy
    - filename
  - timestamp:
      format: RFC3339Nano
      source: time
  - output:
      source: output